services:
    _defaults:
        public: false

    oro_asset_bundle.asset_config.cache:
        class: Oro\Bundle\AssetBundle\Cache\AssetConfigCache
        arguments:
            - '@kernel'

    oro_asset_bundle.asset_config.cache_warmer:
        class: Oro\Bundle\AssetBundle\Cache\AssetConfigCacheWarmer
        arguments:
            - '@oro_asset_bundle.asset_config.cache'
        tags:
            - { name: kernel.cache_warmer, priority: 0 }

    Oro\Bundle\AssetBundle\Command\OroAssetsBuildCommand:
        arguments:
            - '@oro_asset.node_process_factory'
            - '@oro_asset_bundle.asset_config.cache'
            - '%oro_asset.npm_path%'
            - '%oro_asset.build_timeout%'
            - '%oro_asset.npm_install_timeout%'
        tags:
            - { name: console.command, command: 'oro:assets:build' }

    oro_asset.node_process_factory:
        class: Oro\Bundle\AssetBundle\NodeProcessFactory
        arguments:
            - '%oro_asset.nodejs_path%'
