config:
    paths:
        'oroconfig/js/form/config-form': 'bundles/oroconfig/js/form/config-form.js'
        'oroconfig/js/app/views/configuration-tree-view': 'bundles/oroconfig/js/app/views/configuration-tree-view.js'
